In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
#1
print('Question 1:')
df=pd.read_csv('seismic_bumps.csv')
#dropping 8 columns as most values are 0 and are giving singular cov matrix
df1=df.drop(df.loc[:,'nbumps':'nbumps89'].columns,axis = 1) 
x_label=df['class']
y = x_label  #for convenience 
x=df1.drop(['class'],axis = 1)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42, shuffle=True)
train = pd.concat((x_train, y_train), axis = 1)
test = pd.concat((x_test, y_test), axis = 1)
train.to_csv('seismic-bumps-train.csv')
test.to_csv('seismic-bumps-test.csv')
# a & b
print('a & b:')
for k in range(1,6,2):
    knn1 = KNeighborsClassifier(n_neighbors=k)
    knn1.fit(x_train, y_train)
    y_pred = knn1.predict(x_test)
    print('Confusion matrix for k =', k)
    print(confusion_matrix(y_test, y_pred))
    a = accuracy_score(y_test, y_pred)
    print("Accuracy Score is",a,'\n')
    
#2
print('Question 2:')
#Min_Max Normalization exluding class attribute
x_trainnormal=((x_train-x_train.min())/(x_train.max()-x_train.min()))*(1-0)+0 
train_normal = pd.concat((x_trainnormal,y_train),axis = 1) #included class attribute
#Min_Max Normalization of test data using min, max of train dataset
x_testnormal=((x_test-x_train.min())/(x_train.max()-x_train.min()))*(1-0)+0
test_normal = pd.concat((x_testnormal,y_test),axis = 1)

train_normal.to_csv('seismic-bumps-train-Normalised.csv')
test_normal.to_csv(' seismic-bumps-test-normalised.csv')




Question 1:
a & b:
Confusion matrix for k = 1
[[675  48]
 [ 47   6]]
Accuracy Score is 0.8775773195876289 

Confusion matrix for k = 3
[[708  15]
 [ 51   2]]
Accuracy Score is 0.9149484536082474 

Confusion matrix for k = 5
[[716   7]
 [ 52   1]]
Accuracy Score is 0.9239690721649485 

Question 2:
